// Runner shapes for problems whose I/O is a data structure rather than a
// flat array: linked lists and binary trees.
//
// Wire formats (mirrored exactly by scripts/seed/libStruct.js, which computes
// expected outputs from reference solutions):
//
//   linked list : "n" then n integers.           Output: values, space-joined.
//   binary tree : "n" then n tokens in level     Output: level-order tokens
//                 order, where "null" marks an           with trailing nulls
//                 absent child.                          trimmed.
//
// An empty list/tree is n = 0 and prints as an empty line.
//
// Every language builds the structure from stdin, hands the user's `solution`
// the same shape LeetCode would, and serializes the result canonically — so a
// correct solution in any language produces byte-identical output.

// ---------------------------------------------------------------------------
// Shared scaffolding per language
// ---------------------------------------------------------------------------
const C_LIST = [
    'struct ListNode { int val; struct ListNode *next; };',
    'static struct ListNode* build_list(int *v, int n) {',
    '    struct ListNode *head = NULL, *tail = NULL;',
    '    for (int i = 0; i < n; i++) {',
    '        struct ListNode *node = malloc(sizeof(struct ListNode));',
    '        node->val = v[i]; node->next = NULL;',
    '        if (!head) { head = tail = node; } else { tail->next = node; tail = node; }',
    '    }',
    '    return head;',
    '}',
    'static void print_list(struct ListNode *h) {',
    '    int first = 1;',
    '    for (; h; h = h->next) { if (!first) printf(" "); printf("%d", h->val); first = 0; }',
    '    printf("\\n");',
    '}',
    'static int read_ints(int **out) {',
    '    int n; if (scanf("%d", &n) != 1) { *out = NULL; return 0; }',
    '    int *v = malloc(sizeof(int) * (n > 0 ? n : 1));',
    '    for (int i = 0; i < n; i++) scanf("%d", &v[i]);',
    '    *out = v; return n;',
    '}'
].join('\n');

const CPP_LIST = [
    'struct ListNode { int val; ListNode *next; ListNode(int x) : val(x), next(nullptr) {} };',
    'static ListNode* buildList(const vector<int>& v) {',
    '    ListNode *head = nullptr, *tail = nullptr;',
    '    for (int x : v) { ListNode *n = new ListNode(x); if (!head) head = tail = n; else { tail->next = n; tail = n; } }',
    '    return head;',
    '}',
    'static void printList(ListNode *h) {',
    '    bool first = true;',
    '    for (; h; h = h->next) { if (!first) cout << " "; cout << h->val; first = false; }',
    '    cout << "\\n";',
    '}',
    'static vector<int> readInts() {',
    '    int n; if (!(cin >> n)) return {};',
    '    vector<int> v(n);',
    '    for (int i = 0; i < n; i++) cin >> v[i];',
    '    return v;',
    '}'
].join('\n');

const JAVA_LIST = [
    'class ListNode {',
    '    int val; ListNode next;',
    '    ListNode() {}',
    '    ListNode(int val) { this.val = val; }',
    '    ListNode(int val, ListNode next) { this.val = val; this.next = next; }',
    '}'
].join('\n');

const JAVA_LIST_HELPERS = [
    '    static ListNode buildList(int[] v) {',
    '        ListNode head = null, tail = null;',
    '        for (int x : v) { ListNode n = new ListNode(x); if (head == null) { head = tail = n; } else { tail.next = n; tail = n; } }',
    '        return head;',
    '    }',
    '    static void printList(ListNode h) {',
    '        StringBuilder sb = new StringBuilder();',
    '        boolean first = true;',
    '        for (; h != null; h = h.next) { if (!first) sb.append(" "); sb.append(h.val); first = false; }',
    '        System.out.println(sb);',
    '    }'
].join('\n');

const JS_LIST = [
    'function ListNode(val, next) { this.val = val === undefined ? 0 : val; this.next = next === undefined ? null : next; }',
    'function __buildList(v) {',
    '  let head = null, tail = null;',
    '  for (const x of v) { const n = new ListNode(x); if (!head) { head = tail = n; } else { tail.next = n; tail = n; } }',
    '  return head;',
    '}',
    'function __printList(h) {',
    '  const out = [];',
    '  for (; h; h = h.next) out.push(h.val);',
    "  console.log(out.join(' '));",
    '}'
].join('\n');

const PY_LIST = [
    'class ListNode:',
    '    def __init__(self, val=0, next=None):',
    '        self.val = val',
    '        self.next = next',
    '',
    'def __build_list(v):',
    '    head = tail = None',
    '    for x in v:',
    '        n = ListNode(x)',
    '        if head is None:',
    '            head = tail = n',
    '        else:',
    '            tail.next = n',
    '            tail = n',
    '    return head',
    '',
    'def __print_list(h):',
    '    out = []',
    '    while h:',
    '        out.append(h.val)',
    '        h = h.next',
    "    print(' '.join(map(str, out)))"
].join('\n');

// --- trees -----------------------------------------------------------------
const C_TREE = [
    'struct TreeNode { int val; struct TreeNode *left, *right; };',
    'static struct TreeNode* new_node(int v) {',
    '    struct TreeNode *n = malloc(sizeof(struct TreeNode));',
    '    n->val = v; n->left = n->right = NULL; return n;',
    '}',
    '// Level-order build: "null" tokens mark absent children.',
    'static struct TreeNode* build_tree(char **tok, int n) {',
    '    if (n == 0 || strcmp(tok[0], "null") == 0) return NULL;',
    '    struct TreeNode *root = new_node(atoi(tok[0]));',
    '    struct TreeNode **q = malloc(sizeof(void*) * (n + 1));',
    '    int head = 0, tail = 0; q[tail++] = root;',
    '    int i = 1;',
    '    while (head < tail && i < n) {',
    '        struct TreeNode *cur = q[head++];',
    '        if (i < n) { if (strcmp(tok[i], "null")) { cur->left = new_node(atoi(tok[i])); q[tail++] = cur->left; } i++; }',
    '        if (i < n) { if (strcmp(tok[i], "null")) { cur->right = new_node(atoi(tok[i])); q[tail++] = cur->right; } i++; }',
    '    }',
    '    return root;',
    '}',
    'static void print_tree(struct TreeNode *root) {',
    '    if (!root) { printf("\\n"); return; }',
    '    struct TreeNode **q = malloc(sizeof(void*) * 20000);',
    '    char **out = malloc(sizeof(char*) * 20000);',
    '    int head = 0, tail = 0, m = 0;',
    '    q[tail++] = root;',
    '    while (head < tail) {',
    '        struct TreeNode *cur = q[head++];',
    '        if (cur) {',
    '            out[m] = malloc(16); sprintf(out[m], "%d", cur->val); m++;',
    '            q[tail++] = cur->left; q[tail++] = cur->right;',
    '        } else { out[m] = malloc(8); strcpy(out[m], "null"); m++; }',
    '    }',
    '    while (m > 0 && strcmp(out[m-1], "null") == 0) m--;',
    '    for (int i = 0; i < m; i++) { if (i) printf(" "); printf("%s", out[i]); }',
    '    printf("\\n");',
    '}',
    'static int read_tokens(char ***out) {',
    '    int n; if (scanf("%d", &n) != 1) { *out = NULL; return 0; }',
    '    char **t = malloc(sizeof(char*) * (n > 0 ? n : 1));',
    '    for (int i = 0; i < n; i++) { t[i] = malloc(16); scanf("%15s", t[i]); }',
    '    *out = t; return n;',
    '}'
].join('\n');

const CPP_TREE = [
    'struct TreeNode { int val; TreeNode *left, *right; TreeNode(int x) : val(x), left(nullptr), right(nullptr) {} };',
    'static TreeNode* buildTree(const vector<string>& tok) {',
    '    if (tok.empty() || tok[0] == "null") return nullptr;',
    '    TreeNode *root = new TreeNode(stoi(tok[0]));',
    '    queue<TreeNode*> q; q.push(root);',
    '    size_t i = 1;',
    '    while (!q.empty() && i < tok.size()) {',
    '        TreeNode *cur = q.front(); q.pop();',
    '        if (i < tok.size()) { if (tok[i] != "null") { cur->left = new TreeNode(stoi(tok[i])); q.push(cur->left); } i++; }',
    '        if (i < tok.size()) { if (tok[i] != "null") { cur->right = new TreeNode(stoi(tok[i])); q.push(cur->right); } i++; }',
    '    }',
    '    return root;',
    '}',
    'static void printTree(TreeNode *root) {',
    '    vector<string> out;',
    '    if (root) {',
    '        queue<TreeNode*> q; q.push(root);',
    '        while (!q.empty()) {',
    '            TreeNode *cur = q.front(); q.pop();',
    '            if (cur) { out.push_back(to_string(cur->val)); q.push(cur->left); q.push(cur->right); }',
    '            else out.push_back("null");',
    '        }',
    '        while (!out.empty() && out.back() == "null") out.pop_back();',
    '    }',
    '    for (size_t i = 0; i < out.size(); i++) { if (i) cout << " "; cout << out[i]; }',
    '    cout << "\\n";',
    '}',
    'static vector<string> readTokens() {',
    '    int n; if (!(cin >> n)) return {};',
    '    vector<string> t(n);',
    '    for (int i = 0; i < n; i++) cin >> t[i];',
    '    return t;',
    '}'
].join('\n');

const JAVA_TREE = [
    'class TreeNode {',
    '    int val; TreeNode left, right;',
    '    TreeNode() {}',
    '    TreeNode(int val) { this.val = val; }',
    '    TreeNode(int val, TreeNode left, TreeNode right) { this.val = val; this.left = left; this.right = right; }',
    '}'
].join('\n');

const JAVA_TREE_HELPERS = [
    '    static TreeNode buildTree(String[] tok) {',
    '        if (tok.length == 0 || tok[0].equals("null")) return null;',
    '        TreeNode root = new TreeNode(Integer.parseInt(tok[0]));',
    '        java.util.Deque<TreeNode> q = new java.util.ArrayDeque<>();',
    '        q.add(root);',
    '        int i = 1;',
    '        while (!q.isEmpty() && i < tok.length) {',
    '            TreeNode cur = q.poll();',
    '            if (i < tok.length) { if (!tok[i].equals("null")) { cur.left = new TreeNode(Integer.parseInt(tok[i])); q.add(cur.left); } i++; }',
    '            if (i < tok.length) { if (!tok[i].equals("null")) { cur.right = new TreeNode(Integer.parseInt(tok[i])); q.add(cur.right); } i++; }',
    '        }',
    '        return root;',
    '    }',
    '    static void printTree(TreeNode root) {',
    '        java.util.List<String> out = new java.util.ArrayList<>();',
    '        if (root != null) {',
    '            // ArrayDeque forbids null elements, and this queue must carry',
    '            // absent children so they serialize as "null" — LinkedList allows it.',
    '            java.util.List<TreeNode> q = new java.util.LinkedList<>();',
    '            q.add(root);',
    '            int h = 0;',
    '            while (h < q.size()) {',
    '                TreeNode cur = q.get(h++);',
    '                if (cur != null) { out.add(String.valueOf(cur.val)); q.add(cur.left); q.add(cur.right); }',
    '                else out.add("null");',
    '            }',
    '            while (!out.isEmpty() && out.get(out.size()-1).equals("null")) out.remove(out.size()-1);',
    '        }',
    '        System.out.println(String.join(" ", out));',
    '    }'
].join('\n');

const JS_TREE = [
    'function TreeNode(val, left, right) { this.val = val === undefined ? 0 : val; this.left = left === undefined ? null : left; this.right = right === undefined ? null : right; }',
    'function __buildTree(tok) {',
    "  if (!tok.length || tok[0] === 'null') return null;",
    '  const root = new TreeNode(parseInt(tok[0], 10));',
    '  const q = [root];',
    '  let i = 1, h = 0;',
    '  while (h < q.length && i < tok.length) {',
    '    const cur = q[h++];',
    "    if (i < tok.length) { if (tok[i] !== 'null') { cur.left = new TreeNode(parseInt(tok[i], 10)); q.push(cur.left); } i++; }",
    "    if (i < tok.length) { if (tok[i] !== 'null') { cur.right = new TreeNode(parseInt(tok[i], 10)); q.push(cur.right); } i++; }",
    '  }',
    '  return root;',
    '}',
    'function __printTree(root) {',
    '  const out = [];',
    '  if (root) {',
    '    const q = [root];',
    '    let h = 0;',
    '    while (h < q.length) {',
    '      const cur = q[h++];',
    '      if (cur) { out.push(String(cur.val)); q.push(cur.left || null); q.push(cur.right || null); }',
    "      else out.push('null');",
    '    }',
    "    while (out.length && out[out.length-1] === 'null') out.pop();",
    '  }',
    "  console.log(out.join(' '));",
    '}'
].join('\n');

const PY_TREE = [
    'class TreeNode:',
    '    def __init__(self, val=0, left=None, right=None):',
    '        self.val = val',
    '        self.left = left',
    '        self.right = right',
    '',
    'def __build_tree(tok):',
    "    if not tok or tok[0] == 'null':",
    '        return None',
    '    root = TreeNode(int(tok[0]))',
    '    q = [root]',
    '    i, h = 1, 0',
    '    while h < len(q) and i < len(tok):',
    '        cur = q[h]; h += 1',
    '        if i < len(tok):',
    "            if tok[i] != 'null':",
    '                cur.left = TreeNode(int(tok[i])); q.append(cur.left)',
    '            i += 1',
    '        if i < len(tok):',
    "            if tok[i] != 'null':",
    '                cur.right = TreeNode(int(tok[i])); q.append(cur.right)',
    '            i += 1',
    '    return root',
    '',
    'def __print_tree(root):',
    '    out = []',
    '    if root:',
    '        q = [root]; h = 0',
    '        while h < len(q):',
    '            cur = q[h]; h += 1',
    '            if cur:',
    '                out.append(str(cur.val)); q.append(cur.left); q.append(cur.right)',
    '            else:',
    "                out.append('null')",
    "        while out and out[-1] == 'null':",
    '            out.pop()',
    "    print(' '.join(out))"
].join('\n');

const C_HEAD = ['#include <stdio.h>', '#include <stdlib.h>', '#include <string.h>', '#include <stdbool.h>', ''];
const CPP_HEAD = ['#include <bits/stdc++.h>', 'using namespace std;', ''];

// ---------------------------------------------------------------------------
// Shapes
// ---------------------------------------------------------------------------
const structRunners = {

    // list -> list   (reverse-linked-list, reorder-list)
    'list-to-list': {
        c: (src) => [...C_HEAD, C_LIST, '', src, '',
            'int main() {', '    int *v; int n = read_ints(&v);',
            '    print_list(solution(build_list(v, n)));', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_LIST, '', src, '',
            'int main() {', '    vector<int> v = readInts();',
            '    printList(Solution().solution(buildList(v)));', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE_UNUSED(), JAVA_LIST, '', src, '',
            'public class Main {', JAVA_LIST_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); int[] v = new int[n];',
            '        for (int i = 0; i < n; i++) v[i] = sc.nextInt();',
            '        printList(new Solution().solution(buildList(v)));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_LIST, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/).map(Number);",
            'const _n = _t[0] || 0;',
            '__printList(solution(__buildList(_t.slice(1, 1 + _n))));'].join('\n'),
        python: (src) => [PY_LIST, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0]) if data else 0',
            '__print_list(solution(__build_list([int(x) for x in data[1:1+n]])))'].join('\n')
    },

    // list + k -> list   (remove-nth-node, reverse-nodes-in-k-group)
    'list-k-to-list': {
        c: (src) => [...C_HEAD, C_LIST, '', src, '',
            'int main() {', '    int *v; int n = read_ints(&v);', '    int k; scanf("%d", &k);',
            '    print_list(solution(build_list(v, n), k));', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_LIST, '', src, '',
            'int main() {', '    vector<int> v = readInts(); int k; cin >> k;',
            '    printList(Solution().solution(buildList(v), k));', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_LIST, '', src, '',
            'public class Main {', JAVA_LIST_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); int[] v = new int[n];',
            '        for (int i = 0; i < n; i++) v[i] = sc.nextInt();',
            '        int k = sc.nextInt();',
            '        printList(new Solution().solution(buildList(v), k));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_LIST, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/).map(Number);",
            'const _n = _t[0] || 0;',
            '__printList(solution(__buildList(_t.slice(1, 1 + _n)), _t[1 + _n]));'].join('\n'),
        python: (src) => [PY_LIST, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0])',
            'k = int(data[1+n])',
            '__print_list(solution(__build_list([int(x) for x in data[1:1+n]]), k))'].join('\n')
    },

    // two lists -> list   (merge-two-sorted-lists, add-two-numbers)
    'two-lists-to-list': {
        c: (src) => [...C_HEAD, C_LIST, '', src, '',
            'int main() {', '    int *a; int n = read_ints(&a);', '    int *b; int m = read_ints(&b);',
            '    print_list(solution(build_list(a, n), build_list(b, m)));', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_LIST, '', src, '',
            'int main() {', '    vector<int> a = readInts(); vector<int> b = readInts();',
            '    printList(Solution().solution(buildList(a), buildList(b)));', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_LIST, '', src, '',
            'public class Main {', JAVA_LIST_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); int[] a = new int[n];',
            '        for (int i = 0; i < n; i++) a[i] = sc.nextInt();',
            '        int m = sc.nextInt(); int[] b = new int[m];',
            '        for (int i = 0; i < m; i++) b[i] = sc.nextInt();',
            '        printList(new Solution().solution(buildList(a), buildList(b)));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_LIST, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/).map(Number);",
            'let _i = 0;',
            'const _n = _t[_i++]; const _a = _t.slice(_i, _i + _n); _i += _n;',
            'const _m = _t[_i++]; const _b = _t.slice(_i, _i + _m); _i += _m;',
            '__printList(solution(__buildList(_a), __buildList(_b)));'].join('\n'),
        python: (src) => [PY_LIST, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'i = 0',
            'n = int(data[i]); i += 1',
            'a = [int(x) for x in data[i:i+n]]; i += n',
            'm = int(data[i]); i += 1',
            'b = [int(x) for x in data[i:i+m]]; i += m',
            '__print_list(solution(__build_list(a), __build_list(b)))'].join('\n')
    },

    // k lists -> list   (merge-k-sorted-lists)
    'lists-to-list': {
        c: (src) => [...C_HEAD, C_LIST, '', src, '',
            'int main() {', '    int k; if (scanf("%d", &k) != 1) return 0;',
            '    struct ListNode **lists = malloc(sizeof(void*) * (k > 0 ? k : 1));',
            '    for (int j = 0; j < k; j++) { int *v; int n = read_ints(&v); lists[j] = build_list(v, n); }',
            '    print_list(solution(lists, k));', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_LIST, '', src, '',
            'int main() {', '    int k; cin >> k;', '    vector<ListNode*> lists;',
            '    for (int j = 0; j < k; j++) lists.push_back(buildList(readInts()));',
            '    printList(Solution().solution(lists));', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_LIST, '', src, '',
            'public class Main {', JAVA_LIST_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int k = sc.nextInt();',
            '        ListNode[] lists = new ListNode[k];',
            '        for (int j = 0; j < k; j++) {',
            '            int n = sc.nextInt(); int[] v = new int[n];',
            '            for (int i = 0; i < n; i++) v[i] = sc.nextInt();',
            '            lists[j] = buildList(v);',
            '        }',
            '        printList(new Solution().solution(lists));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_LIST, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/).map(Number);",
            'let _i = 0; const _k = _t[_i++]; const _lists = [];',
            'for (let j = 0; j < _k; j++) { const n = _t[_i++]; _lists.push(__buildList(_t.slice(_i, _i + n))); _i += n; }',
            '__printList(solution(_lists));'].join('\n'),
        python: (src) => [PY_LIST, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'i = 0',
            'k = int(data[i]); i += 1',
            'lists = []',
            'for _ in range(k):',
            '    n = int(data[i]); i += 1',
            '    lists.append(__build_list([int(x) for x in data[i:i+n]])); i += n',
            '__print_list(solution(lists))'].join('\n')
    },

    // list + cycle position -> bool   (linked-list-cycle)
    'list-cycle-to-bool': {
        c: (src) => [...C_HEAD, C_LIST, '', src, '',
            'int main() {', '    int *v; int n = read_ints(&v);', '    int pos; scanf("%d", &pos);',
            '    struct ListNode *head = build_list(v, n);',
            '    if (pos >= 0 && head) {',
            '        struct ListNode *tail = head, *target = head;',
            '        while (tail->next) tail = tail->next;',
            '        for (int i = 0; i < pos; i++) target = target->next;',
            '        tail->next = target;',
            '    }',
            '    puts(solution(head) ? "true" : "false");', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_LIST, '', src, '',
            'int main() {', '    vector<int> v = readInts(); int pos; cin >> pos;',
            '    ListNode *head = buildList(v);',
            '    if (pos >= 0 && head) {',
            '        ListNode *tail = head, *target = head;',
            '        while (tail->next) tail = tail->next;',
            '        for (int i = 0; i < pos; i++) target = target->next;',
            '        tail->next = target;',
            '    }',
            '    cout << (Solution().solution(head) ? "true" : "false") << endl;', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_LIST, '', src, '',
            'public class Main {', JAVA_LIST_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); int[] v = new int[n];',
            '        for (int i = 0; i < n; i++) v[i] = sc.nextInt();',
            '        int pos = sc.nextInt();',
            '        ListNode head = buildList(v);',
            '        if (pos >= 0 && head != null) {',
            '            ListNode tail = head, target = head;',
            '            while (tail.next != null) tail = tail.next;',
            '            for (int i = 0; i < pos; i++) target = target.next;',
            '            tail.next = target;',
            '        }',
            '        System.out.println(new Solution().solution(head));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_LIST, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/).map(Number);",
            'const _n = _t[0] || 0;',
            'const _head = __buildList(_t.slice(1, 1 + _n));',
            'const _pos = _t[1 + _n];',
            'if (_pos >= 0 && _head) {',
            '  let tail = _head, target = _head;',
            '  while (tail.next) tail = tail.next;',
            '  for (let i = 0; i < _pos; i++) target = target.next;',
            '  tail.next = target;',
            '}',
            "console.log(solution(_head) ? 'true' : 'false');"].join('\n'),
        python: (src) => [PY_LIST, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0])',
            'head = __build_list([int(x) for x in data[1:1+n]])',
            'pos = int(data[1+n])',
            'if pos >= 0 and head:',
            '    tail = head',
            '    while tail.next:',
            '        tail = tail.next',
            '    target = head',
            '    for _ in range(pos):',
            '        target = target.next',
            '    tail.next = target',
            "print('true' if solution(head) else 'false')"].join('\n')
    },

    // tree -> int
    'tree-to-int': {
        c: (src) => [...C_HEAD, C_TREE, '', src, '',
            'int main() {', '    char **t; int n = read_tokens(&t);',
            '    printf("%d\\n", solution(build_tree(t, n)));', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_TREE, '', src, '',
            'int main() {', '    vector<string> t = readTokens();',
            '    cout << Solution().solution(buildTree(t)) << endl;', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE, '', src, '',
            'public class Main {', JAVA_TREE_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); String[] t = new String[n];',
            '        for (int i = 0; i < n; i++) t[i] = sc.next();',
            '        System.out.println(new Solution().solution(buildTree(t)));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_TREE, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/);",
            'const _n = parseInt(_t[0], 10) || 0;',
            'console.log(solution(__buildTree(_t.slice(1, 1 + _n))));'].join('\n'),
        python: (src) => [PY_TREE, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0]) if data else 0',
            'print(solution(__build_tree(data[1:1+n])))'].join('\n')
    },

    // tree -> bool
    'tree-to-bool': {
        c: (src) => [...C_HEAD, C_TREE, '', src, '',
            'int main() {', '    char **t; int n = read_tokens(&t);',
            '    puts(solution(build_tree(t, n)) ? "true" : "false");', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_TREE, '', src, '',
            'int main() {', '    vector<string> t = readTokens();',
            '    cout << (Solution().solution(buildTree(t)) ? "true" : "false") << endl;', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE, '', src, '',
            'public class Main {', JAVA_TREE_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); String[] t = new String[n];',
            '        for (int i = 0; i < n; i++) t[i] = sc.next();',
            '        System.out.println(new Solution().solution(buildTree(t)));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_TREE, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/);",
            'const _n = parseInt(_t[0], 10) || 0;',
            "console.log(solution(__buildTree(_t.slice(1, 1 + _n))) ? 'true' : 'false');"].join('\n'),
        python: (src) => [PY_TREE, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0]) if data else 0',
            "print('true' if solution(__build_tree(data[1:1+n])) else 'false')"].join('\n')
    },

    // tree -> tree   (invert-binary-tree)
    'tree-to-tree': {
        c: (src) => [...C_HEAD, C_TREE, '', src, '',
            'int main() {', '    char **t; int n = read_tokens(&t);',
            '    print_tree(solution(build_tree(t, n)));', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_TREE, '', src, '',
            'int main() {', '    vector<string> t = readTokens();',
            '    printTree(Solution().solution(buildTree(t)));', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE, '', src, '',
            'public class Main {', JAVA_TREE_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); String[] t = new String[n];',
            '        for (int i = 0; i < n; i++) t[i] = sc.next();',
            '        printTree(new Solution().solution(buildTree(t)));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_TREE, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/);",
            'const _n = parseInt(_t[0], 10) || 0;',
            '__printTree(solution(__buildTree(_t.slice(1, 1 + _n))));'].join('\n'),
        python: (src) => [PY_TREE, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0]) if data else 0',
            '__print_tree(solution(__build_tree(data[1:1+n])))'].join('\n')
    },

    // two trees -> bool   (same-tree, subtree-of-another-tree)
    'two-trees-to-bool': {
        c: (src) => [...C_HEAD, C_TREE, '', src, '',
            'int main() {', '    char **a; int n = read_tokens(&a);', '    char **b; int m = read_tokens(&b);',
            '    puts(solution(build_tree(a, n), build_tree(b, m)) ? "true" : "false");', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_TREE, '', src, '',
            'int main() {', '    vector<string> a = readTokens(); vector<string> b = readTokens();',
            '    cout << (Solution().solution(buildTree(a), buildTree(b)) ? "true" : "false") << endl;', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE, '', src, '',
            'public class Main {', JAVA_TREE_HELPERS,
            '    static String[] readTok(Scanner sc) { int n = sc.nextInt(); String[] t = new String[n]; for (int i = 0; i < n; i++) t[i] = sc.next(); return t; }',
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        TreeNode a = buildTree(readTok(sc));',
            '        TreeNode b = buildTree(readTok(sc));',
            '        System.out.println(new Solution().solution(a, b));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_TREE, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/);",
            'let _i = 0;',
            'const _n = parseInt(_t[_i++], 10); const _a = _t.slice(_i, _i + _n); _i += _n;',
            'const _m = parseInt(_t[_i++], 10); const _b = _t.slice(_i, _i + _m); _i += _m;',
            "console.log(solution(__buildTree(_a), __buildTree(_b)) ? 'true' : 'false');"].join('\n'),
        python: (src) => [PY_TREE, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'i = 0',
            'n = int(data[i]); i += 1',
            'a = data[i:i+n]; i += n',
            'm = int(data[i]); i += 1',
            'b = data[i:i+m]; i += m',
            "print('true' if solution(__build_tree(a), __build_tree(b)) else 'false')"].join('\n')
    },

    // tree + k -> int   (kth-smallest-element-in-a-bst)
    'tree-k-to-int': {
        c: (src) => [...C_HEAD, C_TREE, '', src, '',
            'int main() {', '    char **t; int n = read_tokens(&t);', '    int k; scanf("%d", &k);',
            '    printf("%d\\n", solution(build_tree(t, n), k));', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_TREE, '', src, '',
            'int main() {', '    vector<string> t = readTokens(); int k; cin >> k;',
            '    cout << Solution().solution(buildTree(t), k) << endl;', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE, '', src, '',
            'public class Main {', JAVA_TREE_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); String[] t = new String[n];',
            '        for (int i = 0; i < n; i++) t[i] = sc.next();',
            '        int k = sc.nextInt();',
            '        System.out.println(new Solution().solution(buildTree(t), k));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_TREE, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/);",
            'const _n = parseInt(_t[0], 10) || 0;',
            'console.log(solution(__buildTree(_t.slice(1, 1 + _n)), parseInt(_t[1 + _n], 10)));'].join('\n'),
        python: (src) => [PY_TREE, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0])',
            'print(solution(__build_tree(data[1:1+n]), int(data[1+n])))'].join('\n')
    },

    // tree + two node values -> int   (lowest-common-ancestor-of-a-bst)
    'tree-two-vals-to-int': {
        c: (src) => [...C_HEAD, C_TREE, '', src, '',
            'int main() {', '    char **t; int n = read_tokens(&t);', '    int p, q; scanf("%d %d", &p, &q);',
            '    printf("%d\\n", solution(build_tree(t, n), p, q));', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_TREE, '', src, '',
            'int main() {', '    vector<string> t = readTokens(); int p, q; cin >> p >> q;',
            '    cout << Solution().solution(buildTree(t), p, q) << endl;', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE, '', src, '',
            'public class Main {', JAVA_TREE_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); String[] t = new String[n];',
            '        for (int i = 0; i < n; i++) t[i] = sc.next();',
            '        int p = sc.nextInt(), q = sc.nextInt();',
            '        System.out.println(new Solution().solution(buildTree(t), p, q));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_TREE, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/);",
            'const _n = parseInt(_t[0], 10) || 0;',
            'console.log(solution(__buildTree(_t.slice(1, 1 + _n)), parseInt(_t[1 + _n], 10), parseInt(_t[2 + _n], 10)));'].join('\n'),
        python: (src) => [PY_TREE, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0])',
            'print(solution(__build_tree(data[1:1+n]), int(data[1+n]), int(data[2+n])))'].join('\n')
    },

    // tree -> flat int array   (right-side-view)
    'tree-to-array': {
        c: (src) => [...C_HEAD, C_TREE, '', src, '',
            'int main() {', '    char **t; int n = read_tokens(&t);',
            '    int returnSize = 0;',
            '    int *r = solution(build_tree(t, n), &returnSize);',
            '    for (int i = 0; i < returnSize; i++) { if (i) printf(" "); printf("%d", r[i]); }',
            '    printf("\\n");', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_TREE, '', src, '',
            'int main() {', '    vector<string> t = readTokens();',
            '    vector<int> r = Solution().solution(buildTree(t));',
            '    for (size_t i = 0; i < r.size(); i++) { if (i) cout << " "; cout << r[i]; }',
            '    cout << endl;', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE, '', src, '',
            'public class Main {', JAVA_TREE_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); String[] t = new String[n];',
            '        for (int i = 0; i < n; i++) t[i] = sc.next();',
            '        java.util.List<Integer> r = new Solution().solution(buildTree(t));',
            '        StringBuilder sb = new StringBuilder();',
            '        for (int i = 0; i < r.size(); i++) { if (i > 0) sb.append(" "); sb.append(r.get(i)); }',
            '        System.out.println(sb);',
            '    }', '}'].join('\n'),
        js: (src) => [JS_TREE, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/);",
            'const _n = parseInt(_t[0], 10) || 0;',
            "console.log(solution(__buildTree(_t.slice(1, 1 + _n))).join(' '));"].join('\n'),
        python: (src) => [PY_TREE, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0]) if data else 0',
            "print(' '.join(map(str, solution(__build_tree(data[1:1+n])))))"].join('\n')
    },

    // tree -> rows, order preserved   (level-order traversal)
    'tree-to-levels': {
        c: (src) => [...C_HEAD, C_TREE, '', src, '',
            'int main() {', '    char **t; int n = read_tokens(&t);',
            '    int returnSize = 0; int *colSizes = NULL;',
            '    int **rows = solution(build_tree(t, n), &returnSize, &colSizes);',
            '    for (int i = 0; i < returnSize; i++) {',
            '        for (int j = 0; j < colSizes[i]; j++) { if (j) printf(" "); printf("%d", rows[i][j]); }',
            '        printf("\\n");',
            '    }', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_TREE, '', src, '',
            'int main() {', '    vector<string> t = readTokens();',
            '    vector<vector<int>> rows = Solution().solution(buildTree(t));',
            '    for (auto &row : rows) {',
            '        for (size_t j = 0; j < row.size(); j++) { if (j) cout << " "; cout << row[j]; }',
            '        cout << "\\n";',
            '    }', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE, '', src, '',
            'public class Main {', JAVA_TREE_HELPERS,
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int n = sc.nextInt(); String[] t = new String[n];',
            '        for (int i = 0; i < n; i++) t[i] = sc.next();',
            '        java.util.List<java.util.List<Integer>> rows = new Solution().solution(buildTree(t));',
            '        StringBuilder sb = new StringBuilder();',
            '        for (java.util.List<Integer> row : rows) {',
            '            for (int j = 0; j < row.size(); j++) { if (j > 0) sb.append(" "); sb.append(row.get(j)); }',
            '            sb.append("\\n");',
            '        }',
            '        System.out.print(sb);',
            '    }', '}'].join('\n'),
        js: (src) => [JS_TREE, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/);",
            'const _n = parseInt(_t[0], 10) || 0;',
            "console.log(solution(__buildTree(_t.slice(1, 1 + _n))).map(r => r.join(' ')).join('\\n'));"].join('\n'),
        python: (src) => [PY_TREE, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'n = int(data[0]) if data else 0',
            'rows = solution(__build_tree(data[1:1+n]))',
            "print('\\n'.join(' '.join(map(str, r)) for r in rows))"].join('\n')
    },

    // two int arrays -> tree   (construct from preorder + inorder)
    'two-arrays-to-tree': {
        c: (src) => [...C_HEAD, C_TREE,
            'static int read_ints2(int **out) {',
            '    int n; if (scanf("%d", &n) != 1) { *out = NULL; return 0; }',
            '    int *v = malloc(sizeof(int) * (n > 0 ? n : 1));',
            '    for (int i = 0; i < n; i++) scanf("%d", &v[i]);',
            '    *out = v; return n;',
            '}', '', src, '',
            'int main() {', '    int *a; int n = read_ints2(&a);', '    int *b; int m = read_ints2(&b);',
            '    print_tree(solution(a, n, b, m));', '    return 0;', '}'].join('\n'),
        cpp: (src) => [...CPP_HEAD, CPP_TREE,
            'static vector<int> readInts2() { int n; if (!(cin >> n)) return {}; vector<int> v(n); for (int i = 0; i < n; i++) cin >> v[i]; return v; }',
            '', src, '',
            'int main() {', '    vector<int> a = readInts2(); vector<int> b = readInts2();',
            '    printTree(Solution().solution(a, b));', '    return 0;', '}'].join('\n'),
        java: (src) => ['import java.util.*;', '', JAVA_TREE, '', src, '',
            'public class Main {', JAVA_TREE_HELPERS,
            '    static int[] readInts(Scanner sc) { int n = sc.nextInt(); int[] v = new int[n]; for (int i = 0; i < n; i++) v[i] = sc.nextInt(); return v; }',
            '    public static void main(String[] args) {',
            '        Scanner sc = new Scanner(System.in);',
            '        int[] a = readInts(sc), b = readInts(sc);',
            '        printTree(new Solution().solution(a, b));',
            '    }', '}'].join('\n'),
        js: (src) => [JS_TREE, '', src, '',
            "const _t = require('fs').readFileSync(0, 'utf8').trim().split(/\\s+/).map(Number);",
            'let _i = 0;',
            'const _n = _t[_i++]; const _a = _t.slice(_i, _i + _n); _i += _n;',
            'const _m = _t[_i++]; const _b = _t.slice(_i, _i + _m); _i += _m;',
            '__printTree(solution(_a, _b));'].join('\n'),
        python: (src) => [PY_TREE, '', src, '',
            'import sys',
            'data = sys.stdin.read().split()',
            'i = 0',
            'n = int(data[i]); i += 1',
            'a = [int(x) for x in data[i:i+n]]; i += n',
            'm = int(data[i]); i += 1',
            'b = [int(x) for x in data[i:i+m]]; i += m',
            '__print_tree(solution(a, b))'].join('\n')
    }
};

// Java files may only declare each helper class once; the list shapes never
// need TreeNode, so this keeps the two families independent.
function JAVA_TREE_UNUSED() { return ''; }

module.exports = { structRunners };
